import { defineAgent } from "../../core/define-agent.ts";
import { query } from "@anthropic-ai/claude-agent-sdk";

export default defineAgent({
  name: "pr-summary",
  triggers: [{ event: "pull_request", action: "opened" }],
  handler: async (ctx) => {
    const diff = await ctx.diff();
    if (!diff) {
      ctx.logger.info("pr-summary.empty_diff");
      return;
    }

    const startTime = Date.now();
    let summary = "";

    ctx.logger.info("pr-summary.started");

    for await (const msg of query({
      prompt: `Summarise this PR diff in a few bullet points. What changed, which modules are affected, and anything a reviewer should pay attention to.

\`\`\`diff
${diff}
\`\`\``,
      options: {
        model: ctx.model,
        permissionMode: "dontAsk",
        allowedTools: [],
      },
    })) {
      if (msg.type === "result" && msg.subtype === "success") {
        summary = msg.result;
      }
    }

    if (!summary) {
      ctx.logger.error("pr-summary.no_output");
      return;
    }

    await ctx.comment(
      `## PR Summary\n\n${summary}\n\n---\n*Generated by PR Summary Agent*`,
    );
    ctx.logger.info({ elapsedMs: Date.now() - startTime }, "pr-summary.complete");
  },
});
