/**
 * Summarises a PR diff and posts a comment.
 */
import { query } from "@anthropic-ai/claude-agent-sdk";
import { getPrDiff, postComment } from "../../core/gh.ts";
import { logger } from "../../core/logger.ts";

export async function summarisePr(
  repo: string,
  prNumber: number,
  model: string
): Promise<void> {
  const log = logger.child({ event: "summarise", repo, prNumber });

  const diff = await getPrDiff(repo, prNumber);
  if (!diff) {
    log.info("summarise.empty_diff");
    return;
  }

  const startTime = Date.now();
  let summary = "";

  log.info("summarise.started");

  for await (const msg of query({
    prompt: `Summarise this PR diff in a few bullet points. What changed, which modules are affected, and anything a reviewer should pay attention to.

\`\`\`diff
${diff}
\`\`\``,
    options: {
      model,
      permissionMode: "dontAsk",
      allowedTools: [],
    },
  })) {
    if (msg.type === "result" && msg.subtype === "success") {
      summary = msg.result;
    }
  }

  if (!summary) {
    log.error("summarise.no_output");
    return;
  }

  await postComment(repo, prNumber, `## PR Summary\n\n${summary}\n\n---\n*Generated by PR Summary Agent*`);
  log.info({ elapsedMs: Date.now() - startTime }, "summarise.complete");
}
